version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER:  username
      POSTGRES_DB: news

  web:
    build: ./News
    volumes:
      - type: volume
        source: statics
        target: /app/statics
    depends_on:
      - postgres
    environment:
      DJANGO_SUPERUSER_USERNAME: admin_user
      DJANGO_SUPERUSER_PASSWORD: admin_password
      DATABASE_USER: username
      DATABASE_PASS: password
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432

  nginx:
    build: ./Nginx
    volumes:
      - type: volume
        source: statics
        target: /var/statics
    ports:
      - '127.0.0.1:8000:80'
    depends_on:
      - web

  crawler:
    build: ./crawler
    environment:
      API_URL: http://web:8000/api/posts/
      API_USER: username
      API_PASS: password
    depends_on:
      - web

volumes:
  statics: